{% set name = "beniget" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7af11fa8ec7de3d3eb3d98b1e722d15d44017d8b35d8aa11d54f6719b312f22

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    # AttributeError: module 'gast' has no attribute 'MatchStar' which is resolved in gast 0.5.4
    # which 0.5.0 doesn't have
    # https://github.com/serge-sans-paille/gast/blob/1f872364a9964bdb739c4f76d0be463104cc4757/gast/gast.py#L328
    - gast >=0.5.4

test:
  source_files:
    - tests
    - README.rst
  imports:
    - beniget
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/serge-sans-paille/beniget
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extract semantic information about static Python code
  description: |
    Beniget is a collection of Compile-time analyze on Python Abstract Syntax Tree(AST).
    It's a building block to write static analyzer or compiler for Python.
  dev_url: https://github.com/serge-sans-paille/beniget
  doc_url: https://github.com/serge-sans-paille/beniget

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - serge-sans-paille
