{% set name = "beniget" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 350422b0598c92fcc5f8bcaf77f2a62f6744fb8f2fb495b10a50176c1283639f

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - gast >=0.2.2
    - python

test:
  imports:
    - beniget

about:
  home: https://github.com/serge-sans-paille/beniget/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extract semantic information about static Python code

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
