travis:
  secure:
    BINSTAR_TOKEN: lY+007fNHCyIlL+V7yw1tGaKqzqbaAKyCbrRyg/IFdKna1zYqGjdGekXsOOeWt25GTEYGrQfAp+znZKtu6GTAwD+n5FkcddkYUBINvinUUgwOPh97HntJ8boFFePaWnUGZ77vQ7lv1F2FkDOe2nxk3nflnjiWq5djnFNhfN5kOnPDHK+gYWBXgT1jfRrkYFUtDQNULFkJiM26RCjrqP4rUnMHBeIdfmtExRxwZyPa9E+lK/M7dQ07FA5b+r/JN6G7y+S0oEgjzGbezDED4Y9c4iIvA5AeJ9CfqoIXGJ4/KBy25uvwqaBYrcWUtIaXqPuLlJFIBNu9vVCZjzHTmDe2yrm71+Y27YN5UV21pN7fxeomv0IAeZcUgbVcgMdEeKDVV2+YAaVsN72fUo89rSfOGE+CxWKhQHyuE3WSPhvg3C1SdDaypZ1KRF1sOe0Z9/aLssPs4OnqI9TZgJRA/r+qzPcGHBLs432+7AOkRrFH3BjUDi5He2aZibkhLzPA57FhSgFH8ecJZEnQCHxgM+sDx+dSn8lSxBbpW3LF4yimXR5oIyzeZXlNdOVchCv29OyjFmIwtNBQMq2/yaRaqNWdvgQp+Cy6Eu5V32P92/LyxfGjHF1xpe9covHJHs3XrEuJ1OGprVjExWeckSa3OErSedyCxVrpzzbn1ZTI+KdBTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
